# Generated by Django 3.0.3 on 2020-04-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20200423_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
