# Generated by Django 3.0.3 on 2020-03-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20200327_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quests.User'),
        ),
    ]
