# Generated by Django 3.0.3 on 2020-03-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_auto_20200327_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='completion_time',
        ),
    ]
