# Generated by Django 3.0.3 on 2020-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_auto_20200424_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
