# Generated by Django 3.0.3 on 2020-04-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_auto_20200428_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
